import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Menu from "./components/menu/menu";
import Header from "./components/header/header";
import Footer from "./components/footer/Footer,";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ernis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Menu />
        <Header />
     <Footer/>
      </header>
    </>
  );
}
